## <center>2. Основные понятия линейной алгебры: векторы и действия над ними

**Вектор** (В Python) — это набор чисел, записанных в определённом порядке (в столбец или в строку).

In [1]:
import numpy as np

In [2]:
s = np.array([33, 65, 50, 45])
s

array([33, 65, 50, 45])

In [3]:
s[2]

50

In [4]:
len(s)

4

#### Задание 2.1

Дан вектор в Python вида t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13]), содержащий информацию о средней температуре воздуха (в градусах Цельсия) в Риме с января по декабрь включительно. Будем считать, что температура в январе — , то есть отсчёт индексов идёт с нуля.

In [5]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

In [12]:
t[1]

14

### <center>*ГЕОМЕТРИЧЕСКАЯ ИНТЕРПРЕТАЦИЯ ВЕКТОРА. ВЕКТОРНОЕ ПРОСТРАНСТВО

<img src=https://lms.skillfactory.ru/asset-v1:SkillFactory+DST-3.0+28FEB2021+type@asset+block@MATHML_md1_2_3.png>

### <center> БАЗОВЫЕ ОПЕРАЦИИ С ВЕКТОРАМИ

In [13]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
a + b
## array([15, 23, 14,  8])
a - b
## array([ 5, -7, -4, -6])

array([ 5, -7, -4, -6])

In [14]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
c
## array([24. ,  9. , 13.6])

array([24. ,  9. , 13.6])

In [22]:
a = np.array([120, 150, 190])
b = np.array([130, 130, 130])
c = np.array([2, 3, 2.5])
omega = 72
d = c * omega
d = d.astype(int)
a+b+d

array([394, 496, 500])

#### <center> ЛИНЕЙНАЯ КОМБИНАЦИЯ ВЕКТОРОВ

In [23]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
u

array([1800, 3000, 2700])

#### НУЛЕВАЯ ЛИНЕЙНАЯ КОМБИНАЦИЯ

Самое интересное в линейных комбинациях — это особые случаи, а именно **нулевая линейная комбинация**. 

Линейная комбинация векторов называется **нулевой**, если результат линейной комбинации равен нулевому вектору



### Задание 2.7

Найдите линейную комбинацию векторов 

In [24]:
p = np.array([4, 5])
v = np.array([2, 1])
s = np.array([1, 0])
omega1 = 2
omega2 = -3
omega3 = 5
u = omega1*p + omega2*v + omega3*s
u

array([7, 7])

In [25]:
m = np.array([3, 4, 5, 9])
s = np.array([1, 5, 3, 6])
omega_b = 200
omega_s = 400
d = m*omega_b
p = s*omega_s
p - d

array([-200, 1200,  200,  600])

In [28]:
a = np.array([4, 5, -1])
w = np.array([2, 0 , 1])
np.dot(a, w)

7

### <center> СКАЛЯРНОЕ ПРОИЗВЕДЕНИЕ ВЕКТОРОВ

Существует четыре способа умножить векторы между собой:

* Скалярное произведение. Результат — число. 
* Векторное произведение. Результат — вектор.
* Смешанное произведение. Результат — число. 
* Тензорное произведение. Результат — матрица.