In [1]:
import numpy as np

In [2]:
v_1 = np.array([-1,2,-7,9]).T
v_2 = np.array([2,8,2,-1]).T
s = np.dot(v_1, v_2)
s

-9

In [3]:
A = np.array([[1,1],[1,2]])
G = A.T@A
G

array([[2, 3],
       [3, 5]])

In [4]:
A = np.array([[1,2],[3,7]])
A_inv = np.linalg.inv(A)
A_inv

array([[ 7., -2.],
       [-3.,  1.]])

In [5]:
A = np.array([[2,10,-2],[3,2,-2],[8,14,-6]]).T
np.linalg.matrix_rank(A)

2

In [8]:
A = np.array([[1,2],[-3,1],[1,2],[1,-1]])
A

array([[ 1,  2],
       [-3,  1],
       [ 1,  2],
       [ 1, -1]])

In [11]:
G = A.T@A
G

array([[12,  0],
       [ 0, 10]])

In [13]:
G_inv = np.linalg.inv(G)
G_inv

array([[0.08333333, 0.        ],
       [0.        , 0.1       ]])

In [18]:
b = np.array([[1],[4],[5],[0]])
b

array([[1],
       [4],
       [5],
       [0]])

In [21]:
h = A.T@b

In [22]:
G_inv@h

array([[-0.5],
       [ 1.6]])